# Generated by Django 5.2.1 on 2025-06-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_userrole_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Advance (Bonus)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='conveyance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Conveyance Allowance (10%)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payroll',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='House Rent Allowance (20%)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='meal_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Meal Allowance (10%)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Medical Allowance (3%)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='personal_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Personal Pay (5%)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='profession_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='telephone_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Telephone Allowance (2%)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
