# Generated by Django 5.2.1 on 2025-07-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_advance_payroll_bonus_payroll_conveyance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('ANNUAL', 'Annual Leave'), ('UNPAID', 'Unpaid Leave'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
