# Generated by Django 5.2.1 on 2025-08-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_employee_employment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Salary Report', 'Salary Report'), ('Tax Document', 'Tax Document'), ('Bonus Report', 'Bonus Report'), ('Leave Record', 'Leave Record'), ('Other', 'Other')], max_length=50)),
                ('employee', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('HR', 'HR'), ('Finance', 'Finance')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.TextField(blank=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Archived', 'Archived')], default='Active', max_length=20)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='salarycomponent',
            options={'ordering': ['employee']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emergency_contact_name',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='work_email',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='total_earnings',
            new_name='gross_pay',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='total_deduction',
            new_name='net_pay',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='net_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='basic_calculation_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='basic_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.employee'),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='fixed_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='house_rent_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='hra_calculation_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='hra_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='meal_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='monthly_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='personal_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(default='Default Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payroll.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='conveyance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Conveyance Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='days_worked',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='House Rent Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='meal_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Meal Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Medical Allowance'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='personal_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Personal Pay'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='telephone_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Telephone Allowance'),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='calculation_type',
            field=models.CharField(default='FIXED', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='component_type',
            field=models.CharField(default='EARNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='name',
            field=models.CharField(default='Basic Salary', max_length=100),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='payroll',
            table='payroll',
        ),
        migrations.AlterModelTable(
            name='salarycomponent',
            table='salary_components',
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_description', models.TextField(blank=True, null=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'payment_information',
            },
        ),
        migrations.DeleteModel(
            name='FingerprintLog',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
