# Generated by Django 5.2.1 on 2025-08-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycomponent',
            name='calculation_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Basic'), ('PERCENTAGE_CTC', 'Percentage of CTC'), ('CUSTOM', 'Custom Formula')], default='FIXED', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='component_type',
            field=models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], default='EARNING', max_length=20),
        ),
    ]
