# Generated by Django 5.2.1 on 2025-08-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_relax_nulls_on_salarycomponent_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='payroll.employee'),
        ),
        migrations.AlterModelTable(
            name='leave',
            table='leave',
        ),
    ]
