# Generated by Django 5.2.2 on 2025-08-14 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_leave_employee_alter_leave_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='payroll.employee'),
        ),
    ]
